/**
 * Traefik dynamic configuration generator for custom domains.
 *
 * Generates YAML configuration that Traefik's file provider can watch
 * to automatically provision HTTPS routing and Let's Encrypt certificates
 * for user-configured custom domains on sovereign Rivr instances.
 *
 * Architecture:
 * - The app generates config YAML and stores it in the database.
 * - A deploy agent or cron on the host polls the admin endpoint and
 *   writes the YAML to Traefik's dynamic config directory.
 * - Traefik's file provider detects the change and provisions the route.
 *
 * @module traefik-config
 */

/** Default service name for the rivr-person container in docker-compose. */
const DEFAULT_SERVICE_NAME = "rivr-person";

/** Default internal port the Next.js app listens on. */
const DEFAULT_INTERNAL_PORT = 3000;

/** Default entrypoint name for HTTPS in Traefik. */
const ENTRYPOINT_WEBSECURE = "websecure";

/** Default ACME cert resolver name configured in Traefik static config. */
const DEFAULT_CERT_RESOLVER = "letsencrypt";

/**
 * Converts a domain string into a safe slug suitable for use as a
 * Traefik router/service identifier.
 *
 * Rules:
 * - Lowercased
 * - Dots and colons replaced with hyphens
 * - Non-alphanumeric/hyphen characters stripped
 * - Leading/trailing hyphens trimmed
 * - Prefixed with "custom-" to avoid collisions with static routes
 *
 * @param domain - The custom domain (e.g., "rivr.example.com").
 * @returns A safe slug string (e.g., "custom-rivr-example-com").
 */
export function domainToSlug(domain: string): string {
  const base = domain
    .toLowerCase()
    .replace(/[.:]/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  return `custom-${base}`;
}

/**
 * Options for Traefik config generation.
 */
interface TraefikConfigOptions {
  /** Internal service URL override. Defaults to `http://{serviceName}:{port}`. */
  serviceUrl?: string;
  /** Internal port. Defaults to 3000. */
  port?: number;
  /** Traefik entrypoint name. Defaults to "websecure". */
  entrypoint?: string;
  /** ACME cert resolver name. Defaults to "letsencrypt". */
  certResolver?: string;
  /** Additional middleware names to attach to the router. */
  middlewares?: string[];
}

/**
 * Generates Traefik dynamic configuration YAML for a single custom domain.
 *
 * The generated YAML defines:
 * - A router that matches the Host rule for the domain
 * - TLS configuration with Let's Encrypt ACME
 * - A load-balanced service pointing to the internal container
 *
 * @param domain - The custom domain to route (e.g., "rivr.example.com").
 * @param serviceName - The Docker service name (defaults to "rivr-person").
 * @param options - Optional overrides for port, entrypoint, cert resolver, etc.
 * @returns A YAML string suitable for Traefik's file provider.
 */
export function generateTraefikConfig(
  domain: string,
  serviceName: string = DEFAULT_SERVICE_NAME,
  options: TraefikConfigOptions = {}
): string {
  const {
    port = DEFAULT_INTERNAL_PORT,
    entrypoint = ENTRYPOINT_WEBSECURE,
    certResolver = DEFAULT_CERT_RESOLVER,
    serviceUrl,
    middlewares,
  } = options;

  const slug = domainToSlug(domain);
  const routerName = slug;
  const svcName = `${slug}-svc`;
  const targetUrl = serviceUrl || `http://${serviceName}:${port}`;

  const lines: string[] = [
    `# Traefik dynamic config for custom domain: ${domain}`,
    `# Generated by rivr-person at ${new Date().toISOString()}`,
    `http:`,
    `  routers:`,
    `    ${routerName}:`,
    `      rule: "Host(\`${domain}\`)"`,
    `      entrypoints:`,
    `        - ${entrypoint}`,
    `      tls:`,
    `        certResolver: ${certResolver}`,
  ];

  if (middlewares && middlewares.length > 0) {
    lines.push(`      middlewares:`);
    for (const mw of middlewares) {
      lines.push(`        - ${mw}`);
    }
  }

  lines.push(`      service: ${svcName}`);
  lines.push(`  services:`);
  lines.push(`    ${svcName}:`);
  lines.push(`      loadBalancer:`);
  lines.push(`        servers:`);
  lines.push(`          - url: "${targetUrl}"`);

  return lines.join("\n") + "\n";
}

/**
 * Generates a combined Traefik dynamic configuration YAML for multiple
 * custom domains, all routing to the same service.
 *
 * Used by the admin traefik-config endpoint to produce a single file
 * that covers all active custom domains on this instance.
 *
 * @param domains - Array of active custom domain strings.
 * @param serviceName - The Docker service name (defaults to "rivr-person").
 * @param options - Optional overrides.
 * @returns A combined YAML string with routers and services for all domains.
 */
export function generateCombinedTraefikConfig(
  domains: string[],
  serviceName: string = DEFAULT_SERVICE_NAME,
  options: TraefikConfigOptions = {}
): string {
  if (domains.length === 0) {
    return [
      `# No active custom domains configured`,
      `# Generated by rivr-person at ${new Date().toISOString()}`,
      `http:`,
      `  routers: {}`,
      `  services: {}`,
      "",
    ].join("\n");
  }

  const {
    port = DEFAULT_INTERNAL_PORT,
    entrypoint = ENTRYPOINT_WEBSECURE,
    certResolver = DEFAULT_CERT_RESOLVER,
    serviceUrl,
    middlewares,
  } = options;

  const targetUrl = serviceUrl || `http://${serviceName}:${port}`;
  const sharedSvcName = `${domainToSlug(serviceName)}-svc`;

  const lines: string[] = [
    `# Traefik dynamic config for ${domains.length} custom domain(s)`,
    `# Generated by rivr-person at ${new Date().toISOString()}`,
    `http:`,
    `  routers:`,
  ];

  for (const domain of domains) {
    const slug = domainToSlug(domain);
    lines.push(`    ${slug}:`);
    lines.push(`      rule: "Host(\`${domain}\`)"`);
    lines.push(`      entrypoints:`);
    lines.push(`        - ${entrypoint}`);
    lines.push(`      tls:`);
    lines.push(`        certResolver: ${certResolver}`);
    if (middlewares && middlewares.length > 0) {
      lines.push(`      middlewares:`);
      for (const mw of middlewares) {
        lines.push(`        - ${mw}`);
      }
    }
    lines.push(`      service: ${sharedSvcName}`);
  }

  lines.push(`  services:`);
  lines.push(`    ${sharedSvcName}:`);
  lines.push(`      loadBalancer:`);
  lines.push(`        servers:`);
  lines.push(`          - url: "${targetUrl}"`);

  return lines.join("\n") + "\n";
}
