-- Migration 0041: Recovery assertion nonce store (home-side replay protection)
-- Implements GitHub issue rivr-social/rivr-person#17.
--
-- When a sovereign user forgets their local password, global verifies the
-- seed-phrase signature and issues a short-lived, signed `recovery.assertion`
-- (intent = reset-password, exp <= 10 min) that the home instance consumes
-- at POST /api/recovery/accept-reset. To guarantee single-use semantics the
-- home must persist the assertion nonce and reject replays.
--
-- This table stores only the nonce + agentId + expiry — never the assertion
-- body, newPassword, or any secret material. A scheduled prune removes
-- rows past their `expires_at`.
--
-- References:
--   - HANDOFF_2026-04-19_PRISM_RIVR_MCP_CONNECT.md — "Recovery Plan" section 2.
--   - src/lib/recovery/assertion.ts — verification helper + replay check.
--   - src/app/api/recovery/accept-reset/route.ts — home acceptance endpoint.

-- ── recovery_assertion_nonces ────────────────────────────────────
CREATE TABLE IF NOT EXISTS recovery_assertion_nonces (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nonce text NOT NULL,
  agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  issuer_base_url text NOT NULL,
  intent text NOT NULL,
  consumed_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

-- ── Indexes ──────────────────────────────────────────────────────
-- Uniqueness on nonce is the replay guarantee: any duplicate insert
-- triggers a DB error we map to a 409 on the API surface.
CREATE UNIQUE INDEX IF NOT EXISTS recovery_assertion_nonces_nonce_idx
  ON recovery_assertion_nonces (nonce);
-- Fast lookup of per-agent recent usage (for audit / diagnostics).
CREATE INDEX IF NOT EXISTS recovery_assertion_nonces_agent_id_idx
  ON recovery_assertion_nonces (agent_id);
-- Prune path: ORDER BY expires_at ASC; DELETE WHERE expires_at < now().
CREATE INDEX IF NOT EXISTS recovery_assertion_nonces_expires_at_idx
  ON recovery_assertion_nonces (expires_at);

-- ── Column documentation ─────────────────────────────────────────
COMMENT ON TABLE recovery_assertion_nonces IS
  'Single-use nonce record for global-issued recovery assertions consumed by this home instance. Rows are inserted the first time a nonce is accepted; duplicate inserts trip the unique index and cause the accept-reset endpoint to reject the replay with 409.';
COMMENT ON COLUMN recovery_assertion_nonces.nonce IS
  'Opaque, random string from the recovery assertion (generated by global). Unique across the whole table.';
COMMENT ON COLUMN recovery_assertion_nonces.agent_id IS
  'Agent the assertion authorizes. FK-on-delete-cascade so removed accounts do not accumulate nonces.';
COMMENT ON COLUMN recovery_assertion_nonces.issuer_base_url IS
  'Base URL of the global instance that issued the assertion (e.g. https://b.rivr.social). Preserved for audit/forensics even if global moves.';
COMMENT ON COLUMN recovery_assertion_nonces.intent IS
  'Intent string from the assertion payload. Only `reset-password` is accepted today; persisted so future intents can coexist without migration churn.';
COMMENT ON COLUMN recovery_assertion_nonces.consumed_at IS
  'Server timestamp when the assertion was first successfully consumed.';
COMMENT ON COLUMN recovery_assertion_nonces.expires_at IS
  'Mirror of the assertion `exp` — used by the prune worker to remove stale rows safely (the unique constraint already prevents replay while the row lives).';
