import type { BespokeModuleManifest } from "@/lib/bespoke/types";

export const MYPROFILE_MODULE_ID = "rivr.myprofile";

export function getMyProfileModuleManifest(): BespokeModuleManifest {
  return {
    moduleId: MYPROFILE_MODULE_ID,
    version: "0.1.0",
    title: "My Profile",
    auth: "self",
    dataEndpoint: "/api/myprofile",
    manifestEndpoint: "/api/myprofile/manifest",
    description:
      "Stateful harness for bespoke profile interfaces. Exposes the authenticated user's profile data, allowed mutations, and reusable profile-oriented UI components.",
    fields: [
      { id: "name", label: "Name", type: "string", dataPath: "profile.agent.name", editable: true },
      { id: "username", label: "Username", type: "string", dataPath: "profile.agent.metadata.username", editable: true },
      { id: "bio", label: "Bio", type: "string", dataPath: "profile.agent.metadata.bio", editable: true },
      { id: "tagline", label: "Tagline", type: "string", dataPath: "profile.agent.metadata.tagline", editable: true },
      { id: "location", label: "Location", type: "string", dataPath: "profile.agent.metadata.location", editable: true },
      { id: "skills", label: "Skills", type: "string[]", dataPath: "profile.agent.metadata.skills", editable: true },
      { id: "socialLinks", label: "Social Links", type: "json", dataPath: "profile.agent.metadata.socialLinks", editable: true },
      { id: "profilePhotos", label: "Profile Photos", type: "image[]", dataPath: "profile.agent.metadata.profilePhotos", editable: true },
      { id: "geneKeys", label: "Gene Keys", type: "string", dataPath: "profile.agent.metadata.geneKeys", editable: true, hideable: true },
      { id: "humanDesign", label: "Human Design", type: "string", dataPath: "profile.agent.metadata.humanDesign", editable: true, hideable: true },
      { id: "westernAstrology", label: "Western Astrology", type: "string", dataPath: "profile.agent.metadata.westernAstrology", editable: true, hideable: true },
      { id: "vedicAstrology", label: "Vedic Astrology", type: "string", dataPath: "profile.agent.metadata.vedicAstrology", editable: true, hideable: true },
      { id: "ocean", label: "OCEAN", type: "string", dataPath: "profile.agent.metadata.ocean", editable: true, hideable: true },
      { id: "myersBriggs", label: "Myers-Briggs", type: "string", dataPath: "profile.agent.metadata.myersBriggs", editable: true, hideable: true },
      { id: "enneagram", label: "Enneagram", type: "string", dataPath: "profile.agent.metadata.enneagram", editable: true, hideable: true },
      { id: "ethAddress", label: "ETH Address", type: "string", dataPath: "wallet.wallet.ethAddress", editable: true, hideable: true },
    ],
    mutations: [
      {
        id: "action:updateProfileAction",
        label: "Update Profile",
        description: "Full profile/settings mutation for editable self fields.",
        auth: "self",
        kind: "server-action",
        importPath: "@/app/actions/settings",
        exportName: "updateProfileAction",
        fields: [
          { id: "name", label: "Name", type: "string", required: true },
          { id: "username", label: "Username", type: "string", required: true },
          { id: "email", label: "Email", type: "string", required: true },
          { id: "bio", label: "Bio", type: "string", required: true },
          { id: "tagline", label: "Tagline", type: "string" },
          { id: "phone", label: "Phone", type: "string", required: true },
          { id: "skills", label: "Skills", type: "string[]" },
          { id: "geneKeys", label: "Gene Keys", type: "string" },
          { id: "humanDesign", label: "Human Design", type: "string" },
          { id: "westernAstrology", label: "Western Astrology", type: "string" },
          { id: "vedicAstrology", label: "Vedic Astrology", type: "string" },
          { id: "ocean", label: "OCEAN", type: "string" },
          { id: "myersBriggs", label: "Myers-Briggs", type: "string" },
          { id: "enneagram", label: "Enneagram", type: "string" },
          { id: "homeLocale", label: "Home Locale", type: "string" },
          { id: "socialLinks", label: "Social Links", type: "json" },
          { id: "profilePhotos", label: "Profile Photos", type: "image[]" },
          { id: "privacySettings", label: "Privacy Settings", type: "json" },
          { id: "notificationSettings", label: "Notification Settings", type: "json" },
        ],
      },
      {
        id: "action:updateMyProfile",
        label: "Update Basic Profile",
        description: "Minimal self-profile mutation for quick bespoke profile editors.",
        auth: "self",
        kind: "server-action",
        importPath: "@/app/actions/interactions",
        exportName: "updateMyProfile",
        fields: [
          { id: "name", label: "Name", type: "string", required: true },
          { id: "bio", label: "Bio", type: "string", required: true },
          { id: "skills", label: "Skills", type: "string[]", required: true },
          { id: "location", label: "Location", type: "string" },
        ],
      },
      {
        id: "action:updateProfileImageAction",
        label: "Update Profile Image",
        auth: "self",
        kind: "server-action",
        importPath: "@/app/actions/settings",
        exportName: "updateProfileImageAction",
        fields: [
          { id: "field", label: "Image Field", type: "string", required: true, description: "avatar or coverImage" },
          { id: "url", label: "Image URL", type: "url", required: true },
        ],
      },
      {
        id: "action:setEthAddressAction",
        label: "Set ETH Address",
        auth: "self",
        kind: "server-action",
        importPath: "@/app/actions/wallet",
        exportName: "setEthAddressAction",
        fields: [{ id: "ethAddress", label: "ETH Address", type: "string", required: true }],
      },
      {
        id: "action:createGalleryAction",
        label: "Create Gallery",
        auth: "self",
        kind: "server-action",
        importPath: "@/app/actions/interactions",
        exportName: "createGalleryAction",
        fields: [
          { id: "title", label: "Title", type: "string", required: true },
          { id: "groupId", label: "Group ID", type: "string" },
        ],
      },
      {
        id: "action:toggleSaveListing",
        label: "Toggle Save Listing",
        auth: "self",
        kind: "server-action",
        importPath: "@/app/actions/interactions",
        exportName: "toggleSaveListing",
        fields: [{ id: "listingId", label: "Listing ID", type: "string", required: true }],
      },
    ],
    components: [
      { id: "profile-header-card", label: "Profile Header Card", importPath: "@/components/ui/card", exportName: "Card" },
      { id: "post-feed", label: "Post Feed", importPath: "@/components/post-feed", exportName: "PostFeed" },
      { id: "event-feed", label: "Event Feed", importPath: "@/components/event-feed", exportName: "EventFeed" },
      { id: "profile-group-feed", label: "Profile Group Feed", importPath: "@/components/profile-group-feed", exportName: "ProfileGroupFeed" },
      { id: "profile-calendar", label: "Profile Calendar", importPath: "@/components/profile-calendar", exportName: "ProfileCalendar" },
      { id: "offerings-tab", label: "Offerings Tab", importPath: "@/components/offerings-tab", exportName: "OfferingsTab" },
      { id: "persona-manager", label: "Persona Manager", importPath: "@/components/persona-manager", exportName: "PersonaManager" },
      { id: "user-connections", label: "User Connections", importPath: "@/components/user-connections", exportName: "UserConnections" },
      { id: "receipt-card", label: "Receipt Card", importPath: "@/components/receipt-card", exportName: "ReceiptCard" },
      { id: "eth-address-form", label: "ETH Address Form", importPath: "@/components/eth-address-form", exportName: "EthAddressForm" },
      { id: "metamask-connect-button", label: "MetaMask Connect Button", importPath: "@/components/metamask-connect-button", exportName: "MetaMaskConnectButton" },
    ],
    sections: [
      { id: "hero", label: "Hero", dataPath: "profile.agent", defaultComponentId: "profile-header-card", themeable: true },
      { id: "about", label: "About", dataPath: "profile.agent", defaultComponentId: "profile-header-card", hideable: true, themeable: true },
      { id: "persona-insights", label: "Persona Insights", dataPath: "profile.agent.metadata", defaultComponentId: "profile-header-card", hideable: true, themeable: true, description: "Spiritual / personality metadata such as Gene Keys and Myers-Briggs." },
      { id: "photos", label: "Photos", dataPath: "posts.posts", defaultComponentId: "post-feed", hideable: true, themeable: true },
      { id: "posts", label: "Posts", dataPath: "posts.posts", defaultComponentId: "post-feed", hideable: true, themeable: true },
      { id: "docs", label: "Documents", dataPath: "documents", defaultComponentId: "profile-header-card", hideable: true, themeable: true },
      { id: "media", label: "Media", dataPath: "profile.resources", defaultComponentId: "profile-header-card", hideable: true, themeable: true },
      { id: "events", label: "Events", dataPath: "events", defaultComponentId: "event-feed", hideable: true, themeable: true },
      { id: "groups", label: "Groups", dataPath: "groups", defaultComponentId: "profile-group-feed", hideable: true, themeable: true },
      { id: "offerings", label: "Offerings", dataPath: "marketplaceListings", defaultComponentId: "offerings-tab", hideable: true, themeable: true },
      { id: "calendar", label: "Calendar", dataPath: "events", defaultComponentId: "profile-calendar", hideable: true, themeable: true },
      { id: "wallet", label: "Wallet", dataPath: "wallet", defaultComponentId: "profile-header-card", hideable: true, themeable: true },
      { id: "personas", label: "Personas", dataPath: "profile.agent", defaultComponentId: "persona-manager", hideable: true, themeable: true },
      { id: "saved", label: "Saved Listings", dataPath: "savedListingIds", defaultComponentId: "offerings-tab", hideable: true, themeable: true },
      { id: "activity", label: "Activity", dataPath: "profile.recentActivity", defaultComponentId: "profile-header-card", hideable: true, themeable: true },
      { id: "connections", label: "Connections", dataPath: "connections", defaultComponentId: "user-connections", hideable: true, themeable: true },
    ],
    theme: {
      mode: "tokens",
      editableTokens: [
        "color.background",
        "color.foreground",
        "color.primary",
        "color.accent",
        "color.border",
        "radius.card",
        "shadow.card",
      ],
      presets: ["default", "red-gold", "forest-brass", "earth-clay"],
    },
  };
}
